sudo: required
services:
  - docker

before_install:
  - docker build -t sian20r/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sian20r/react-test npm test

after_success:
  - docker build -t sian20r/multi-client ./client
  - docker build -t sian20r/multi-nginx ./nginx
  - docker build -t sian20r/multi-server ./server
  - docker build -t sian20r/multi-worker ./worker
  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push sian20r/multi-client
  - docker push sian20r/multi-nginx
  - docker push sian20r/multi-server
  - docker push sian20r/multi-worker